デザインとバグ修正2
osushi-academy/sushi-chat pull request #533
Opened 2021-09-28 10:09 UTC by yuta-ike

- Messageコンポーネント周りのデザインを修正
- ピン留め解除ボタンを追加
- アイコンをmaterial iconからfeatherにリプレース
- 最新のメッセージへのデザインを修正
- スクロール時のデザインを追加・

close #xxx

## やったこと
- reaction/メッセージの吹き出しのデザイン調整
- ピン留め解除ボタンを追加
![image](https://user-images.githubusercontent.com/38308823/135067608-5d9f3aca-e7dd-4d32-bc55-6b7d2c0bab27.png)
- スクロールバーを非表示
- 一部のアイコンをmaterial iconからfeatherに変更
- 「最新のメッセージへ」のデザインを変更
![image](https://user-images.githubusercontent.com/38308823/135067643-bb35f28f-211c-4446-8fd4-4b77e84797bd.png)

- リアクションやリプライで元のメッセージをクリックした場合に、スクロールに加えて元のメッセージがハイライトされる処理を追加
![image](https://user-images.githubusercontent.com/38308823/135067535-d0354bc5-6dc2-45e2-b17e-d96be050a443.png)

## 参考リンク・補足など

2021-09-28 17:14 UTC, KoukiNAGATA requested changes
2点確認よろしくお願いしますー

2021-09-28 17:14 UTC, KoukiNAGATA commented on app/front/components/UrlToLink.vue
> +        @click.stop
特にユーザーが貼ってくるリンクなので`rel="noopener noreferrer"` つけといた方がよさそう(これまでなんでついてなかったんだろう)

2021-09-28 17:14 UTC, KoukiNAGATA commented on app/front/components/Message.vue
> +            }"
@clickが抜けててリアクションができなくなってる

2021-09-28 17:17 UTC, KoukiNAGATA commented
あと提案:
ピン留めメッセージもリアクションみたいにクリックしたらその場所までスクロールするとよさそう(参考:LINE)

2021-09-28 17:17 UTC, knknk98 reviewed
このプルリクが原因かはわからないけど一番目のトピックだけ
```
【運営Bot】
発表が始まりました！
コメントを投稿して盛り上げましょう 🎉🎉
```
が出てこなくなってる

2021-09-29 04:26 UTC, yuta-ike commented
@knknk98 
> このプルリクが原因かはわからないけど一番目のトピックだけ
【運営Bot】
発表が始まりました！
コメントを投稿して盛り上げましょう 🎉🎉
が出てこなくなってる

手元で再現しないんですが、もう少し詳しく教えてもらって良いですか？

2021-09-29 04:29 UTC, yuta-ike commented
あー多分サーバーサイドの問題なのでissue切っておきます

2021-09-29 04:38 UTC, yuta-ike commented
> あと提案:
ピン留めメッセージもリアクションみたいにクリックしたらその場所までスクロールするとよさそう(参考:LINE)

パッとデザイン思いつかなかった & リアクションと比べて需要は低そうなので一旦issue立てときました〜〜

2021-09-29 05:32 UTC, KoukiNAGATA approved these changes
LGTM！

2021-09-29 05:33 UTC, merged