トピック終了後のコメントのタイムスタンプをundefinedにする
osushi-academy/sushi-chat pull request #593
Opened 2021-10-22 07:17 UTC by yuta-ike

close #565 

## やったこと
- トピック終了後に投稿されたコメントはタイムスタンプを含めない

## 参考リンク・補足など

2021-11-27 12:25 UTC, TOMOFUMI-KONDO approved these changes
LGTM

2021-12-06 14:38 UTC, Eri-0910 requested changes

2021-12-06 14:38 UTC, Eri-0910 commented on app/server/src/domain/room/Room.ts
> +    if (this.topics.find(({ id }) => id === topicId)?.state !== "ongoing") {
`this.topics.find(({ id }) => id === topicId)` が `undefined` の時、
`this.topics.find(({ id }) => id === topicId)?.state` もまた `undefined` で、
`!== "ongoing")` は `true` になりそう。だからテストも落ちてそう。

```
this.topics.find(({ id }) => id === topicId) &&
      this.topics.find(({ id }) => id === topicId)?.state !== "ongoing"
```

かな。

2022-01-05 09:09 UTC, yuta-ike commented on app/server/src/domain/room/Room.ts
> +    if (this.topics.find(({ id }) => id === topicId)?.state !== "ongoing") {
なるほど、ありがとうございます！

2022-01-05 11:47 UTC, yuta-ike commented
@Eri-0910 修正しましたー

2022-01-18 13:13 UTC, Eri-0910 approved these changes

2022-01-18 14:39 UTC, merged