refactor: stylelint導入
osushi-academy/sushi-chat pull request #653
Opened 2022-01-04 15:03 UTC by knknk98

close #582 

## やったこと
StyleLint導入した
SCSSとCSSに対応

- StyleLint拡張入れてたらVSCode上にリアルタイムで赤線でてくる
- 順番も直してくれる

## やっていないこと
既存のSCSSにStyleLintを適用する

## 参考リンク・補足など

2022-01-05 09:29 UTC, yuta-ike requested changes
ESlint / prettierみたいにコマンドラインから実行（yarn xx）できるようにしたさがあります🙏（CIでチェックできるようになるので）

2022-01-05 09:35 UTC, knknk98 commented
@yuta-ike いまって`yarn stylelint  --fix assets/scss/**/**.scss`とかでできてない？？？

2022-01-05 09:39 UTC, yuta-ike commented
あーなるほど確かに。その内容をpackage.jsonに記載しておいてほしいです。（理想は`/app/front`にいるときに、`yarn lint:style`とかで実行できると嬉しいです）
したら毎度引数を書く必要がなくなるのと、設定次第でyarn lintとかでESLintとまとめて一括実行できたり

`app/front/package.json`
![image](https://user-images.githubusercontent.com/38308823/148195596-692c02a5-b8b1-47e8-a3b0-a2946337dfba.png)

2022-01-18 14:11 UTC, yuta-ike approved these changes

2022-01-18 14:11 UTC, yuta-ike commented
スマホ向けデザイン系のPRが収束したらマージで！

2022-01-18 15:07 UTC, yuta-ike commented
#659 に引き継ぎ

2022-01-18 15:07 UTC, closed without merging